//<auto-generated/>
namespace MyCookbook.Data.Migrations
{
    using Microsoft.EntityFrameworkCore.Migrations;

    public partial class AddDescriptionFieldToRecipeEntity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "Recipes",
                maxLength: 2000,
                nullable: false,
                defaultValue: "");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Description",
                table: "Recipes");
        }
    }
}
